export const Actions = {
  SET_ASSET: "SET_ASSET",
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_ACTIVE_CATEGORIES: "SET_ACTIVE_CATEGORIES",
  SET_INSTITUTIONS: "SET_INSTITUTIONS",

  LOAD_STATE: "LOAD_STATE",
  SET_WHOLE_STATE: "SET_WHOLE_STATE",

  SET_NAME: "SET_NAME",
  SET_CURRENCY: "SET_CURRENCY",
  SET_INFLATION: "SET_INFLATION",
  SET_TOTAL: "SET_TOTAL",
  SET_COUNTRY: "SET_COUNTRY",
}
